config/routes.rb
Rails.application.routes.draw do
  resources :kittens

  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to @kitten, notice: "kitten created successfully"
    else
      flash.now[:notice] = "How can you miss that?"
      render :new
    end

  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: "kitten updated successfully"
    else
      flash.now[:notice] = "Are you even trying?"
      render :edit
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path, notice: "kitten deleted"
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= notice %>
<br /><br /><br />
<%= form_with model: kitten do |f| %>
  <% kitten.errors.full_messages_for(:name).each do |message| %>
    <p><%= message %></p>
  <% end %>
  <%= f.label :name, "Name of the kitten:" %>
  <%= f.text_field :name %><br /><br />

  <% kitten.errors.full_messages_for(:age).each do |message| %>
    <p><%= message %></p>
  <% end %>
  <%= f.label :age, "Age of the kitten:" %>
  <%= f.number_field :age %><br /><br />

  <% kitten.errors.full_messages_for(:softness).each do |message| %>
    <p><%= message %></p>
  <% end %>
  <%= f.label :softness, "How soft is the kitten:" %>
  <%= f.number_field :softness %><br /><br />
  
  <% kitten.errors.full_messages_for(:cuteness).each do |message| %>
    <p><%= message %></p>
  <% end %>
  <%= f.label :cuteness, "How cute is the kitten:" %>
  <%= f.number_field :cuteness %><br /><br />

  <%= f.submit "Add the kitten" %>

<% end %>

app/views/kittens/edit.html.erb
<h1>Edit this kitten</h1>
<%= render "form", kitten: @kitten %>
<br /><br />


<%= link_to "Delete this kitten", kitten_path(@kitten),
                                  method: :delete,
                                  data: { confirm: "Are you sure?" }
                                %>

app/views/kittens/index.html.erb
<h1>We have some Kittens here!</h1>
<p><%= notice %></p>
<br /><br />
<% @kittens.each do |kitten| %>
  <h2>Name: <%= kitten.name %></h2>
  <p>Age: <%= kitten.age %></p>
  <p>Softness: <%= kitten.softness %></p>
  <p>Cuteness: <%= kitten.cuteness %></p>
  <h3><%= link_to "Go to kittens page", kitten %></h3>
  <%= link_to "Delete this kitten", kitten_path(kitten),
                                  method: :delete,
                                  data: { confirm: "Are you sure?" }
                                %>
  <br />
<% end %>

<br /><br /><br />

<%= link_to "Create A New Kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Create a new kitten</h1>
<%= render "form", kitten: @kitten %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<p><%= notice %></p>
<h3>Age: <%= @kitten.age %></h2>
<h3>Softness: <%= @kitten.softness %></h2>
<h3>Cuteness: <%= @kitten.cuteness %></h2>

<br /><br /><br />

<%= link_to "Edit this kitten's info", edit_kitten_path %><br />
<%= link_to "Delete this kitten", kitten_path(@kitten),
                                  method: :delete,
                                  data: { confirm: "Are you sure?" }
                                %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>